Configure SAST in `.gitlab-ci.yml`, creating this file if it does not already exist

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,388 +1,295 @@
+# You can override the included template(s) by including variable overrides
+# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
+# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
+# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
+# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
+# Note that environment variables can be set in several places
+# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
 include:
-  - local: '.gitlab-ci-deployment.yml'
-  - local: '.gitlab-ci-seo.yml'
-
+- local: ".gitlab-ci-deployment.yml"
+- local: ".gitlab-ci-seo.yml"
+- template: Security/SAST.gitlab-ci.yml
 stages:
-  - config
-  - test
-  - build
-  - deploy
-  - manual-deploy
-
+- config
+- test
+- build
+- deploy
+- manual-deploy
 workflow:
   rules:
-    # Allow pipeline when triggered from other pipelines (deployment-only-pipeline)
-    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
-    # Allow pipeline when triggered from the gitlab ui to start a pipeline
-    - if: '$CI_PIPELINE_SOURCE == "web"'
-    # Allow Pipeline run when it's scheduled
-    - if: '$CI_PIPELINE_SOURCE == "schedule"'
-    # Allow pipeline for pushing to develop, staging, main branches
-    - if: '$CI_COMMIT_REF_NAME =~ /^(main|staging|develop)$/'
-      when: always
-
-    # Block pipeline creation for all other cases (e.g. feature branches, tags, merge requests)
-    - when: never
-
-
+  - if: $CI_PIPELINE_SOURCE == "pipeline"
+  - if: $CI_PIPELINE_SOURCE == "web"
+  - if: $CI_PIPELINE_SOURCE == "schedule"
+  - if: "$CI_COMMIT_REF_NAME =~ /^(main|staging|develop)$/"
+    when: always
+  - when: never
 variables:
-  ARTIFACT_COMPRESSION_LEVEL: 'fast'
-  CACHE_COMPRESSION_LEVEL: 'fast'
-#  npm_config_cache: '.npm/'
-
-.normal-rules:
+  ARTIFACT_COMPRESSION_LEVEL: fast
+  CACHE_COMPRESSION_LEVEL: fast
+".normal-rules":
   rules:
-    # when ever a pipeline is created run job, even for manual jobs only
-    - when: always
-
-# don't run for deployment only and scheduled pipelines, to avoid making unnecessary changes
-# in production
-.build-rules:
+  - when: always
+".build-rules":
   rules:
-    # don't run when triggered from other pipeline (deployment-only-pipeline)
-    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
-    # don't run when it's scheduled
-    - if: '$CI_PIPELINE_SOURCE == "schedule"'
-      when: never
-
-    # run normal jobs in any other case
-    - when: always
-
-# don't run for scheduled pipelines, to avoid making unnecessary changes in production
-.deployment-rules:
+  - if: $CI_PIPELINE_SOURCE == "pipeline"
+  - if: $CI_PIPELINE_SOURCE == "schedule"
+    when: never
+  - when: always
+".deployment-rules":
   rules:
-    # don't run when it's scheduled
-    - if: '$CI_PIPELINE_SOURCE == "schedule"'
-      when: never
-
-    # run normal jobs in any other case
-    - when: always
-
-# don't run for scheduled pipelines, to avoid making unnecessary changes in production
-.manual-deployment-rules:
+  - if: $CI_PIPELINE_SOURCE == "schedule"
+    when: never
+  - when: always
+".manual-deployment-rules":
   rules:
-    # don't run when it's scheduled
-    - if: '$CI_PIPELINE_SOURCE == "schedule"'
-      when: never
-
-    - when: manual
-
-
+  - if: $CI_PIPELINE_SOURCE == "schedule"
+    when: never
+  - when: manual
 set-vars:
-  stage: .pre
+  stage: ".pre"
   image: alpine:3.20
-  environment: $CI_COMMIT_REF_NAME
-  extends: .normal-rules
-  # for manual jobs add allow_failure so the whole pipeline won't show up as "blocked"
+  environment: "$CI_COMMIT_REF_NAME"
+  extends: ".normal-rules"
   allow_failure: false
   before_script:
-    - >
-      apk add jq yq --no-cache
-      --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
+  - 'apk add jq yq --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
+
+    '
   script:
-    - VERSION=$(jq '.version' package.json --raw-output)
-    # if BUILD_VERSION is alredy set it's overwritten from another pipeline and this has to be used
-    # extract version number from package.json, to make it available in the app
-    # use unset"${BUILD_VERSION" to check if variable is set, will cover both cases null and "unset" / empty string
-    - |
-      if [ unset"${BUILD_VERSION}" == "unset" ]; then
-        echo "BUILD_VERSION=${VERSION}" >> build.env
-        echo "BUILD_VERSION was unset. Set to ${VERSION}."
-        cat build.env
-      else
-        echo "BUILD_VERSION=${BUILD_VERSION}" >> build.env
-        echo "BUILD_VERSION is already set to ${BUILD_VERSION}."
-        cat build.env
-      fi
-    - echo "information environment ${CI_COMMIT_REF_NAME}"
-    - |
-      if [ "${CI_COMMIT_REF_NAME}" == "develop" ]; then
-        echo "CI_COMMIT_REF_NAME=dev" >> build.env
-      fi
-    # move all variables from the CI / CD into the build variables
-    - cat .env >> build.env
-    # bash "source" command loads all the variables from the file
-    - source build.env
-    # set build variables for the package registry
-    - echo "BUILD_NAME=${BUILD_VERSION}.${CI_COMMIT_REF_NAME}" >> build.env
-    - echo "BUILD_ZIP_NAME=envidat-frontend-${BUILD_VERSION}.${CI_COMMIT_REF_NAME}.zip" >> build.env
-    - echo "Matomo token ${MATOMO_TOKEN}."
-    - echo "Matomo siteId ${MATOMO_SITEID}."
-    - echo "content of build.env"
-    - echo "information environment ${CI_COMMIT_REF_NAME}"
-    - cat build.env
+  - VERSION=$(jq '.version' package.json --raw-output)
+  - |
+    if [ unset"${BUILD_VERSION}" == "unset" ]; then
+      echo "BUILD_VERSION=${VERSION}" >> build.env
+      echo "BUILD_VERSION was unset. Set to ${VERSION}."
+      cat build.env
+    else
+      echo "BUILD_VERSION=${BUILD_VERSION}" >> build.env
+      echo "BUILD_VERSION is already set to ${BUILD_VERSION}."
+      cat build.env
+    fi
+  - echo "information environment ${CI_COMMIT_REF_NAME}"
+  - |
+    if [ "${CI_COMMIT_REF_NAME}" == "develop" ]; then
+      echo "CI_COMMIT_REF_NAME=dev" >> build.env
+    fi
+  - cat .env >> build.env
+  - source build.env
+  - echo "BUILD_NAME=${BUILD_VERSION}.${CI_COMMIT_REF_NAME}" >> build.env
+  - echo "BUILD_ZIP_NAME=envidat-frontend-${BUILD_VERSION}.${CI_COMMIT_REF_NAME}.zip"
+    >> build.env
+  - echo "Matomo token ${MATOMO_TOKEN}."
+  - echo "Matomo siteId ${MATOMO_SITEID}."
+  - echo "content of build.env"
+  - echo "information environment ${CI_COMMIT_REF_NAME}"
+  - cat build.env
   artifacts:
     reports:
       dotenv: build.env
-
 modify-env:
   stage: config
   image: python:3.9-alpine3.17
-  environment: $CI_COMMIT_REF_NAME
-  extends: .normal-rules
+  environment: "$CI_COMMIT_REF_NAME"
+  extends: ".normal-rules"
   needs:
-    - set-vars
+  - set-vars
   before_script:
-    - if [ -z "$CI_COMMIT_REF_NAME" ]; then echo "CI_COMMIT_REF_NAME is empty!"; exit 1; fi
-    - echo "CI_COMMIT_REF_NAME is set to $CI_COMMIT_REF_NAME"
-    - pip install --upgrade pip
-    - pip install python-dotenv==0.19.*
+  - if [ -z "$CI_COMMIT_REF_NAME" ]; then echo "CI_COMMIT_REF_NAME is empty!"; exit
+    1; fi
+  - echo "CI_COMMIT_REF_NAME is set to $CI_COMMIT_REF_NAME"
+  - pip install --upgrade pip
+  - pip install python-dotenv==0.19.*
   script:
-    - |
-      python -c "import os
-      import dotenv
+  - |
+    python -c "import os
+    import dotenv
 
-      file = '.env.production'
-      branch = os.getenv('CI_COMMIT_REF_NAME')
+    file = '.env.production'
+    branch = os.getenv('CI_COMMIT_REF_NAME')
 
-      key = 'VITE_DOMAIN'
-      value = 'https://envidat04.wsl.ch'
-      
-      if branch == 'main' or branch == 'beta':
-          value = 'https://envidat.ch'
-      
-      dotenv.set_key(file, key, value, quote_mode='never')
+    key = 'VITE_DOMAIN'
+    value = 'https://envidat04.wsl.ch'
 
-      key = 'VITE_API_ROOT'
-      value = 'https://envidat04.wsl.ch'
-      
-      if branch == 'main' or branch == 'beta':
-          value = 'https://envidat.ch'
+    if branch == 'main' or branch == 'beta':
+        value = 'https://envidat.ch'
 
-      dotenv.set_key(file, key, value, quote_mode='never')
+    dotenv.set_key(file, key, value, quote_mode='never')
 
-      # also set the canonical url with same value as the api root
-      key = 'PUBLIC_ENV__VIKE_BASE_CANONICAL_URL'
-      dotenv.set_key(file, key, value, quote_mode='never')
+    key = 'VITE_API_ROOT'
+    value = 'https://envidat04.wsl.ch'
 
-      key = 'VITE_MATOMO_TOKEN'
-      token = os.getenv('MATOMO_TOKEN')
-      dotenv.set_key(file, key, token, quote_mode='never')
+    if branch == 'main' or branch == 'beta':
+        value = 'https://envidat.ch'
 
-      key = 'VITE_MATOMO_SITEID'
-      token = os.getenv('MATOMO_SITEID')
-      dotenv.set_key(file, key, token, quote_mode='never')
+    dotenv.set_key(file, key, value, quote_mode='never')
 
-      key = 'VITE_CONFIG_URL'
-      value = f'https://frontend-config.s3-zh.os.switch.ch/{branch}.json'
-      dotenv.set_key(file, key, value, quote_mode='never')
+    # also set the canonical url with same value as the api root
+    key = 'PUBLIC_ENV__VIKE_BASE_CANONICAL_URL'
+    dotenv.set_key(file, key, value, quote_mode='never')
 
-      key = 'VITE_BUILD_SOURCEMAPS'
-      value = 'false'
-      
-      if branch == 'staging' or branch == 'develop' or branch == 'dev':
-          value = 'true'
-      
-      dotenv.set_key(file, key, value, quote_mode='never')
+    key = 'VITE_MATOMO_TOKEN'
+    token = os.getenv('MATOMO_TOKEN')
+    dotenv.set_key(file, key, token, quote_mode='never')
 
-      key = 'VITE_GOOGLE_VERIFICATION_KEY'
-      value = os.getenv('GOOGLE_VERIFICATION_KEY')
-      dotenv.set_key(file, key, value, quote_mode='never')
+    key = 'VITE_MATOMO_SITEID'
+    token = os.getenv('MATOMO_SITEID')
+    dotenv.set_key(file, key, token, quote_mode='never')
 
-      key = 'VITE_SEO_BASE'
-      value = 'https://envidat04.wsl.ch/seo'
-      
-      if branch == 'main' or branch == 'beta':
-          value = 'https://envidat.ch/seo'
+    key = 'VITE_CONFIG_URL'
+    value = f'https://frontend-config.s3-zh.os.switch.ch/{branch}.json'
+    dotenv.set_key(file, key, value, quote_mode='never')
 
-      dotenv.set_key(file, key, value, quote_mode='never')
-      
-      "
-    - echo "created content for .env.production:"
-    - cat .env.production
+    key = 'VITE_BUILD_SOURCEMAPS'
+    value = 'false'
+
+    if branch == 'staging' or branch == 'develop' or branch == 'dev':
+        value = 'true'
+
+    dotenv.set_key(file, key, value, quote_mode='never')
+
+    key = 'VITE_GOOGLE_VERIFICATION_KEY'
+    value = os.getenv('GOOGLE_VERIFICATION_KEY')
+    dotenv.set_key(file, key, value, quote_mode='never')
+
+    key = 'VITE_SEO_BASE'
+    value = 'https://envidat04.wsl.ch/seo'
+
+    if branch == 'main' or branch == 'beta':
+        value = 'https://envidat.ch/seo'
+
+    dotenv.set_key(file, key, value, quote_mode='never')
+
+    "
+  - echo "created content for .env.production:"
+  - cat .env.production
   artifacts:
-    name: 'environment variables'
+    name: environment variables
     paths:
-      - .env.production
+    - ".env.production"
   retry:
     max: 2
-
 install-node:
   stage: config
   image: node:20.15.0-alpine3.20
-  environment: $CI_COMMIT_REF_NAME
-  # overwrite the global caching to use push-pull policy
+  environment: "$CI_COMMIT_REF_NAME"
   cache:
-    - key:
-        files:
-          - package-lock.json
-        prefix: 'package-lock'
-      paths:
-        - node_modules/
-      # pull-push to be able to update the node_modules in the cache
-      policy: pull-push
-      untracked: true
-      when: on_success
-  extends: .normal-rules
-  before_script:
-    # disabled the funding check
-    - npm config set fund false
-  script:
-    # - echo "the cache work if node_modules and it's .bin directory are available"
-    # - ls -a
-    # Only run npm ci if node_modules don't come from the cache
-    - |
-      if [ -d "node_modules" ] && [ -d "node_modules/.bin" ]; then
-        if [ "$FORCE_NPM_INSTALL" = "true" ]; then
-          echo "FORCE_NPM_INSTALL $FORCE_NPM_INSTALL so going to run npm ci"
-          npm ci --prefer-offline --no-audit
-        else
-          echo "node_modules and it's .bin directory already exists. Skipping npm ci."
-        fi      
-      else
-        echo "node_modules or it's .bin directory not found. Running npm ci..."
-        npm ci --prefer-offline --no-audit
-      fi
-    # - echo "Check afterwards how the folders are"
-    # - ls -l node_modules
-  artifacts:
-    name: 'node dependencies'
-    # stores node_modules as an artifact to be used in the next jobs
-    # caching isn't always guaranteed to work
+  - key:
+      files:
+      - package-lock.json
+      prefix: package-lock
     paths:
-      - node_modules/**/*  # Include all contents, including hidden files and directories
+    - node_modules/
+    policy: pull-push
+    untracked: true
+    when: on_success
+  extends: ".normal-rules"
+  before_script:
+  - npm config set fund false
+  script:
+  - "if [ -d \"node_modules\" ] && [ -d \"node_modules/.bin\" ]; then\n  if [ \"$FORCE_NPM_INSTALL\"
+    = \"true\" ]; then\n    echo \"FORCE_NPM_INSTALL $FORCE_NPM_INSTALL so going to
+    run npm ci\"\n    npm ci --prefer-offline --no-audit\n  else\n    echo \"node_modules
+    and it's .bin directory already exists. Skipping npm ci.\"\n  fi      \nelse\n
+    \ echo \"node_modules or it's .bin directory not found. Running npm ci...\"\n
+    \ npm ci --prefer-offline --no-audit\nfi\n"
+  artifacts:
+    name: node dependencies
+    paths:
+    - node_modules/**/*
     expire_in: 1 day
   retry:
     max: 2
-
 run-tests:
   stage: test
   image: node:20.15.0-alpine3.20
-  environment: $CI_COMMIT_REF_NAME
-  extends: .normal-rules
+  environment: "$CI_COMMIT_REF_NAME"
+  extends: ".normal-rules"
   needs:
-    - modify-env
-    - install-node
+  - modify-env
+  - install-node
   before_script:
-    - |
-      if [ -d "node_modules" ]; then
-        echo "node_modules directory already exists."
-        ls node_modules/.bin/vitest || echo "/.bin/vitest not found"
-      else
-        echo "node_modules directory not found. Should have got them from the install-node artifact!"
-        ls -a
-      fi
-    # - ls node_modules/ -a
-    # - ls node_modules/.bin/ -a
+  - |
+    if [ -d "node_modules" ]; then
+      echo "node_modules directory already exists."
+      ls node_modules/.bin/vitest || echo "/.bin/vitest not found"
+    else
+      echo "node_modules directory not found. Should have got them from the install-node artifact!"
+      ls -a
+    fi
   script:
-    - npm run test
+  - npm run test
   retry:
     max: 2
-
 build-storybook:
   stage: build
   image: node:20.15.0-alpine3.20
-  environment: $CI_COMMIT_REF_NAME
-  extends: .build-rules
+  environment: "$CI_COMMIT_REF_NAME"
+  extends: ".build-rules"
   needs:
-    # needs the artifact: config and environment variables
-    - modify-env
-    # needs the artifact: node_modules to build storybook
-    - install-node
+  - modify-env
+  - install-node
   before_script:
-    - |
-      if [ -d "node_modules" ]; then
-        echo "node_modules directory already exists."
-        ls node_modules/.bin/storybook || echo "/.bin/storybook not found"
-      else
-        echo "node_modules directory not found. Should have got them from the install-node artifact!"
-        ls -a
-      fi
-    # - ls node_modules/ -a
-    # - ls node_modules/.bin/ -a
+  - |
+    if [ -d "node_modules" ]; then
+      echo "node_modules directory already exists."
+      ls node_modules/.bin/storybook || echo "/.bin/storybook not found"
+    else
+      echo "node_modules directory not found. Should have got them from the install-node artifact!"
+      ls -a
+    fi
   script:
-    # - npm config set cache .npm/
-    # - npm cache verify || true
-    - npm run build-storybook -- -o ./storybook --loglevel warn --disable-telemetry
+  - npm run build-storybook -- -o ./storybook --loglevel warn --disable-telemetry
   artifacts:
-    name: 'storybook build'
-    # keep the storybook for 7 days to be able to trigger the chromatic-deployment
+    name: storybook build
     expire_in: 1 day
-    # stores the storybook build as an artifact to be used in the next stages
     paths:
-      - storybook
+    - storybook
   retry:
     max: 2
-
 build-app:
   stage: build
   image: node:20.15.0-alpine3.20
-  environment: $CI_COMMIT_REF_NAME
-  extends: .build-rules
+  environment: "$CI_COMMIT_REF_NAME"
+  extends: ".build-rules"
   needs:
-    # needs the artifact: config and environment variables
-    - modify-env
-    # needs the artifact: node_modules to build the app
-    - install-node
+  - modify-env
+  - install-node
   before_script:
-    - |
-      if [ -d "node_modules" ]; then
-        echo "node_modules directory already exists."
-        ls node_modules/.bin/vite || echo "/.bin/vite not found"
-      else
-        echo "node_modules directory not found. Should have got them from the install-node artifact!"
-        ls -a
-      fi
-    # - ls node_modules/ -a
-    # - ls node_modules/.bin/ -a
+  - |
+    if [ -d "node_modules" ]; then
+      echo "node_modules directory already exists."
+      ls node_modules/.bin/vite || echo "/.bin/vite not found"
+    else
+      echo "node_modules directory not found. Should have got them from the install-node artifact!"
+      ls -a
+    fi
   script:
-    - npm run build -- --logLevel warn
+  - npm run build -- --logLevel warn
   artifacts:
     name: 'frontend build '
     expire_in: 1 day
-    # stores the built app code
     paths:
-      - dist
+    - dist
   retry:
     max: 2
-
-
 combine-builds:
   stage: build
   image: alpine:3.20
-  environment: $CI_COMMIT_REF_NAME
-  extends: .build-rules
+  environment: "$CI_COMMIT_REF_NAME"
+  extends: ".build-rules"
   variables:
     GIT_STRATEGY: none
   needs:
-    # needs the artifact: the build of the frontend app
-    - job: build-app
-    # needs the artifact: storybook
-    - job: build-storybook
-    # needs the artifact: seo pre-rendered static htmls
-    - job: build-seo
-      optional: true
+  - job: build-app
+  - job: build-storybook
+  - job: build-seo
+    optional: true
   script:
-    #- echo "Check for the artifacts in the filesystem"
-    # - ls -l
-    # - ls dist/ -l
-    # - ls storybook/ -l
-    # copy all files from the dist folder into root
-    - cp -r dist/* ./
-    # - ls -l
-    # remove the dist folder recursively
-    - rm -rf dist
-    # - ls -la
+  - cp -r dist/* ./
+  - rm -rf dist
   artifacts:
-    name: 'frontend build $CI_COMMIT_REF_NAME'
+    name: frontend build $CI_COMMIT_REF_NAME
     expire_in: 1 day
-    # stores the combined built code
     paths:
-      - ./
-#tag-commit-sha:
-#  extends: .normal-rules
-#  stage: package
-#  image: regclient/regctl:v0.3-alpine
-#  variables:
-#    GIT_STRATEGY: none
-#  before_script:
-#    - export REG_HOST=${INTERNAL_REG%/*}
-#    - >
-#      echo "{\"hosts\":{\"${REG_HOST}\":{\"tls\":\"enabled\",\"hostname\":
-#      \"${REG_HOST}\",\"user\":\"${IMAGE_REGISTRY_USER}\",\"pass\":
-#      \"${IMAGE_REGISTRY_PASS}\"}}}" >> /home/appuser/.regctl/config.json
-#  script:
-#      - >
-#        regctl --verbosity debug image copy
-#        "${IMAGE_NAME}" "${INTERNAL_REG}/envidat-frontend:${CI_COMMIT_SHA}"
-
+    - "./"
+sast:
+  stage: test
