CI: added specific echo for .bin folder

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -157,6 +157,11 @@ install-node:
   script:
     - echo "the cache work if node_modules and .npm/ folders are available"
     - ls -a
+    - npm ci --prefer-offline --no-audit
+    - echo "Check afterwards how the folders are"
+    - ls -a
+    - ls
+
     # Only run npm ci if node_modules don't come from the cache
     - |
       if [ -d "node_modules" ]; then
@@ -192,7 +197,8 @@ run-tests:
   before_script:
     - |
       if [ -d "node_modules" ]; then
-        echo "node_modules directory already exists. Everything is correct."
+        echo "node_modules directory already exists."
+        ls node_modules/.bin/vitest || echo "/.bin/vitest not found"
       else
         echo "node_modules directory not found. Should have got them from the install-node artifact!"
         ls -a
@@ -216,7 +222,8 @@ build-storybook:
   before_script:
     - |
       if [ -d "node_modules" ]; then
-        echo "node_modules directory already exists. Everything is correct."
+        echo "node_modules directory already exists."
+        ls node_modules/.bin/storybook || echo "/.bin/storybook not found"
       else
         echo "node_modules directory not found. Should have got them from the install-node artifact!"
         ls -a
@@ -249,7 +256,8 @@ build-app:
   before_script:
     - |
       if [ -d "node_modules" ]; then
-        echo "node_modules directory already exists. Everything is correct."
+        echo "node_modules directory already exists."
+        ls node_modules/.bin/vite || echo "/.bin/vite not found"
       else
         echo "node_modules directory not found. Should have got them from the install-node artifact!"
         ls -a
