CI: removed always installing again; added echo for debugging

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -157,11 +157,10 @@ install-node:
   script:
     - echo "the cache work if node_modules and .npm/ folders are available"
     - ls -a
-    - npm ci --prefer-offline --no-audit
-    - echo "Check afterwards how the folders are"
-    - ls -a
-    - ls
-
+    - ls node_modules/.bin/ || echo "/.bin/ not found"
+    #- npm ci --prefer-offline --no-audit
+    #- echo "Check afterwards how the folders are"
+    #- ls node_modules/.bin/ || echo "/.bin/ not found"
     # Only run npm ci if node_modules don't come from the cache
     - |
       if [ -d "node_modules" ]; then
